### ISSUE TITLE
Do not cancel promise once timeout fires

### ISSUE THREAD

**Issue by clue** [clue/php-promise-timer#9]
Currently, the promise will be cancelled (edit: ~~rejected~~) once the timeout fires. This is debatable, but IMHO the name "timeout" implies that we either wait for the promise to settle within the timeout or will never care about its (possible) future result.

Arguably, another use case would be "checking" whether a promise settles within a given time frame. I'd like to put this out here to see if anybody happens to have any thoughts and/or actual use cases.

Also refs https://github.com/clue/php-block-react/issues/4

**Comment by clue** [comment]
I think these are actually two independent use cases that should be clearly separated.

As such, I'd vote against a boolean flag (boolean trap?) and vote for two distinct methods similar to this:

```
timeout($promise, $time, $loop);
timeoutWillCancel($promise, $time, $loop);
```

The *default* should probably *not* cancel any promises, as this is the default promise behavior (e.g. `Promise\all()`). (Warning, BC break ahead).

**Comment by jsor** [comment]
> Currently, the promise will be rejected once the timeout fires

Should this read as "...the promise will be __cancelled__ once..."? As i understand it, the returned promise will be __always__ rejected, but the `cancel()` call on the original promise is the difference between the 2 functions.

:+1: for 2 functions instead of a boolean.

**Comment by clue** [comment]
> Should this read as "...the promise will be cancelled once..."? 

Indeed, thanks for spotting, I've fixed the typo in the OP :)

Other than that, thanks for the feedback! Looks like we have the same understanding.

> :+1: for 2 functions instead of a boolean.

I've toyed around with this but have yet to come up with some decent function names, so perhaps you happen to have any ideas?

The original name used to be `Timeout\await()` and a second `Timeout\awaitOrCancel()` would make sense. Now that the original function is being renamed to `Timer\timeout()` (see #10), I'm unsure how to name the second one?

**Comment by jsor** [comment]
IMHO, the default behaviour (`Timer\timeout()`) should be cancellation of the promise. This is similar to the "timeout" behaviour i'm used to (ie. for HTTP requests, database/socket connections etc.).

To be honest, i can't think of any use cases for __not__ cancelling a promise. Maybe go with `timeout` only and add another function later if there are requests for it.

**Comment by clue** [comment]
> To be honest, i can't think of any use cases for not cancelling a promise. 

Well, I guess I must have been overthinking this?! :) Admittedly, all my use cases actually also assume the canceling behavior.

Thanks for chiming in, very much appreciated!

I have a working prototype for this locally, but will postpone this for now, until we have a valid use case.

**Comment by clue** [comment]
I think we agree on this:

* Cancelling the input promise should be possible (irrespective of the timeout handling)
* Once the timer fires, the input promise should be cancelled and the result rejected (as discussed above, also the current behavior)

Cancelling the resulting timeout promise should also be possible (this has no effect as of yet).
The effect on the resulting timeout promise is pretty easy: abort all timers and reject with an Exception describing the cancellation.

However, it's a bit unclear which effect this should have on the input promise.

Two options:
* Only cancel the resulting timeout promise but leave the input promise alone
* Cancelling the timeout promise should also cancel the input promise

I guess this time both might have valid uses? :)

**Comment by clue** [comment]
Example code:

```php
$input = fetchFromRemoteApi();
$timeout = Timer\timeout($input, 5.0, $loop);

$timeout->cancel();
```

The `$timeout` promise promise should be cancelled and rejected.

Should the `$input` promise be cancelled and rejected?

Two possible interpretations:

* We cancelled only the timeout timer: `$input` should be left alone
* We cancelled the whole operation: `$input` should also be cancelled (and possibly rejected)

**Comment by clue** [comment]
Let's consider some use cases where the `timeout()` function will be used in the real world.

Here's a gist of how a `TimeoutConnector` could possibly work: https://gist.github.com/clue/75d00d9c2ca2e931661c#file-timeoutconnector-php-L20

In cases like these, it's probably safe to assume that if you cancel the resulting `$timeout` promise, the `$input` promise should also be cancelled.

As such, I'm voting for making this the default.

I'm still curious if we come up with some use cases where the other behavior makes sense.

**Comment by clue** [comment]
Edit: This is quite intertwined with #3. I have accidentally posted some comments here, that have now been moved over instead.

**Comment by clue** [comment]
I think we agree here. I guess the confusion can be cleared up by providing some documentation (see #14).

I'd like to make this ticket actionable. IMO we should focus on the main use case (as discussed above) here and close the ticket now that we agree on this. The other use case can be addressed in a separate ticket once deemed useful.
